# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: av_channel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'av_channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61v_channel.proto\x12\x03\x61\x61s\"_\n\x15\x41VChannelSetupRequest\x12\x1e\n\x16maxUnframedPayloadSize\x18\x01 \x02(\x05\x12\x11\n\tsessionId\x18\x02 \x02(\x05\x12\x13\n\x0b\x63odecConfig\x18\x03 \x02(\x05\"[\n\x16\x41VChannelSetupResponse\x12\x11\n\tmediaType\x18\x01 \x02(\x05\x12\x0e\n\x06status\x18\x02 \x02(\x05\x12\x1e\n\x16maxUnframedPayloadSize\x18\x03 \x01(\x05\";\n\x11VideoFocusRequest\x12\x11\n\tfocusMode\x18\x01 \x01(\x05\x12\x13\n\x0bunrequested\x18\x02 \x01(\x08\"<\n\x12VideoFocusResponse\x12\x11\n\tfocusMode\x18\x01 \x01(\x05\x12\x13\n\x0bunrequested\x18\x02 \x01(\x08\">\n\x14VideoFocusIndication\x12\x11\n\tfocusMode\x18\x01 \x02(\x05\x12\x13\n\x0bunrequested\x18\x02 \x02(\x08\"K\n\x18\x41VChannelStartIndication\x12\x0f\n\x07session\x18\x01 \x02(\x05\x12\x1e\n\x16videoFocusRequestState\x18\x02 \x02(\x05\"*\n\x17\x41VChannelStopIndication\x12\x0f\n\x07session\x18\x01 \x02(\x05\";\n\x14\x41VMediaAckIndication\x12\x0f\n\x07session\x18\x01 \x02(\x05\x12\x12\n\nvalueBytes\x18\x02 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'av_channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELSETUPREQUEST']._serialized_start=25
  _globals['_AVCHANNELSETUPREQUEST']._serialized_end=120
  _globals['_AVCHANNELSETUPRESPONSE']._serialized_start=122
  _globals['_AVCHANNELSETUPRESPONSE']._serialized_end=213
  _globals['_VIDEOFOCUSREQUEST']._serialized_start=215
  _globals['_VIDEOFOCUSREQUEST']._serialized_end=274
  _globals['_VIDEOFOCUSRESPONSE']._serialized_start=276
  _globals['_VIDEOFOCUSRESPONSE']._serialized_end=336
  _globals['_VIDEOFOCUSINDICATION']._serialized_start=338
  _globals['_VIDEOFOCUSINDICATION']._serialized_end=400
  _globals['_AVCHANNELSTARTINDICATION']._serialized_start=402
  _globals['_AVCHANNELSTARTINDICATION']._serialized_end=477
  _globals['_AVCHANNELSTOPINDICATION']._serialized_start=479
  _globals['_AVCHANNELSTOPINDICATION']._serialized_end=521
  _globals['_AVMEDIAACKINDICATION']._serialized_start=523
  _globals['_AVMEDIAACKINDICATION']._serialized_end=582
# @@protoc_insertion_point(module_scope)
