# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: input_channel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'input_channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13input_channel.proto\x12\x03\x61\x61s\"8\n\rTouchLocation\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\x11\n\tpointerId\x18\x03 \x02(\x05\"a\n\nTouchEvent\x12)\n\rtouchLocation\x18\x01 \x03(\x0b\x32\x12.aas.TouchLocation\x12\x13\n\x0btouchAction\x18\x02 \x02(\x05\x12\x13\n\x0b\x61\x63tionIndex\x18\x03 \x01(\x05\"_\n\x14InputEventIndication\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12#\n\ntouchEvent\x18\x02 \x01(\x0b\x32\x0f.aas.TouchEvent\x12\x0f\n\x07keyCode\x18\x03 \x01(\x05\"\"\n\x0e\x42indingRequest\x12\x10\n\x08scanCode\x18\x01 \x03(\x05\"!\n\x0f\x42indingResponse\x12\x0e\n\x06status\x18\x01 \x02(\x05*V\n\x0bTouchAction\x12\x16\n\x12TOUCH_ACTION_PRESS\x10\x01\x12\x18\n\x14TOUCH_ACTION_RELEASE\x10\x02\x12\x15\n\x11TOUCH_ACTION_MOVE\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'input_channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOUCHACTION']._serialized_start=353
  _globals['_TOUCHACTION']._serialized_end=439
  _globals['_TOUCHLOCATION']._serialized_start=28
  _globals['_TOUCHLOCATION']._serialized_end=84
  _globals['_TOUCHEVENT']._serialized_start=86
  _globals['_TOUCHEVENT']._serialized_end=183
  _globals['_INPUTEVENTINDICATION']._serialized_start=185
  _globals['_INPUTEVENTINDICATION']._serialized_end=280
  _globals['_BINDINGREQUEST']._serialized_start=282
  _globals['_BINDINGREQUEST']._serialized_end=316
  _globals['_BINDINGRESPONSE']._serialized_start=318
  _globals['_BINDINGRESPONSE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
