# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import service_descriptor_pb2 as service__descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontrol_service.proto\x12\x03\x61\x61s\x1a\x18service_descriptor.proto\"\x1c\n\x0cSSLHandshake\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"(\n\x16\x41uthCompleteIndication\x12\x0e\n\x06status\x18\x01 \x02(\x05\"?\n\x17ServiceDiscoveryRequest\x12\x11\n\tphoneName\x18\x04 \x01(\t\x12\x11\n\tphoneType\x18\x05 \x01(\t\"\xbe\x02\n\x18ServiceDiscoveryResponse\x12(\n\x08services\x18\x01 \x03(\x0b\x32\x16.aas.ServiceDescriptor\x12\x14\n\x0cheadUnitName\x18\x02 \x02(\t\x12\x10\n\x08\x63\x61rModel\x18\x03 \x02(\t\x12\x0f\n\x07\x63\x61rYear\x18\x04 \x02(\t\x12\x11\n\tcarSerial\x18\x05 \x02(\t\x12\x1c\n\x14leftHandDriveVehicle\x18\x06 \x02(\x08\x12\x1c\n\x14headUnitManufacturer\x18\x07 \x02(\t\x12\x15\n\rheadUnitModel\x18\x08 \x02(\t\x12\x0f\n\x07swBuild\x18\t \x02(\t\x12\x11\n\tswVersion\x18\n \x02(\t\x12\"\n\x1a\x63\x61nPlayNativeMediaDuringVR\x18\x0b \x02(\x08\x12\x11\n\thideClock\x18\x0c \x01(\x08\"&\n\x12\x43hannelOpenRequest\x12\x10\n\x08priority\x18\x01 \x02(\x05\"%\n\x13\x43hannelOpenResponse\x12\x0e\n\x06status\x18\x01 \x02(\x05\".\n\x0bPingRequest\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"!\n\x0cPingResponse\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\"&\n\x16NavigationFocusRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\"\'\n\x17NavigationFocusResponse\x12\x0c\n\x04type\x18\x01 \x02(\x05\"!\n\x0fShutdownRequest\x12\x0e\n\x06reason\x18\x01 \x02(\x05\"\"\n\x10ShutdownResponse\x12\x0e\n\x06reason\x18\x01 \x02(\x05\"#\n\x13VoiceSessionRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\"?\n\x11\x41udioFocusRequest\x12\x12\n\nfocusState\x18\x01 \x02(\x05\x12\x16\n\x0e\x61udioFocusType\x18\x02 \x02(\x05\"(\n\x12\x41udioFocusResponse\x12\x12\n\nfocusState\x18\x01 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SSLHANDSHAKE']._serialized_start=56
  _globals['_SSLHANDSHAKE']._serialized_end=84
  _globals['_AUTHCOMPLETEINDICATION']._serialized_start=86
  _globals['_AUTHCOMPLETEINDICATION']._serialized_end=126
  _globals['_SERVICEDISCOVERYREQUEST']._serialized_start=128
  _globals['_SERVICEDISCOVERYREQUEST']._serialized_end=191
  _globals['_SERVICEDISCOVERYRESPONSE']._serialized_start=194
  _globals['_SERVICEDISCOVERYRESPONSE']._serialized_end=512
  _globals['_CHANNELOPENREQUEST']._serialized_start=514
  _globals['_CHANNELOPENREQUEST']._serialized_end=552
  _globals['_CHANNELOPENRESPONSE']._serialized_start=554
  _globals['_CHANNELOPENRESPONSE']._serialized_end=591
  _globals['_PINGREQUEST']._serialized_start=593
  _globals['_PINGREQUEST']._serialized_end=639
  _globals['_PINGRESPONSE']._serialized_start=641
  _globals['_PINGRESPONSE']._serialized_end=674
  _globals['_NAVIGATIONFOCUSREQUEST']._serialized_start=676
  _globals['_NAVIGATIONFOCUSREQUEST']._serialized_end=714
  _globals['_NAVIGATIONFOCUSRESPONSE']._serialized_start=716
  _globals['_NAVIGATIONFOCUSRESPONSE']._serialized_end=755
  _globals['_SHUTDOWNREQUEST']._serialized_start=757
  _globals['_SHUTDOWNREQUEST']._serialized_end=790
  _globals['_SHUTDOWNRESPONSE']._serialized_start=792
  _globals['_SHUTDOWNRESPONSE']._serialized_end=826
  _globals['_VOICESESSIONREQUEST']._serialized_start=828
  _globals['_VOICESESSIONREQUEST']._serialized_end=863
  _globals['_AUDIOFOCUSREQUEST']._serialized_start=865
  _globals['_AUDIOFOCUSREQUEST']._serialized_end=928
  _globals['_AUDIOFOCUSRESPONSE']._serialized_start=930
  _globals['_AUDIOFOCUSRESPONSE']._serialized_end=970
# @@protoc_insertion_point(module_scope)
